// Code generated by goctl. DO NOT EDIT.
package types

type NewAccountRequest struct {
	Algo string `form:"algo"`
	Name string `form:"name"`
}

type NewAccountData struct {
	PubKeyPath  string `json:"pub_key_path"`
	PrivKeyPath string `json:"priv_key_path"`
	Address     string `json:"address"`
}

type NewAccountResponse struct {
	Code int             `json:"code"`
	Msg  string          `json:"msg"`
	Data *NewAccountData `json:"data,omitempty"` // 为空时不返回
}
